[package]
name = "examples"
version = "0.1.0"
authors = ["bjoernQ <bjoern.quentin@mobile-j.de>"]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.75"

[profile.release]
debug = true
lto = "fat"
opt-level = "s"


[profile.release.package.esp-wifi]
opt-level = 3

[profile.dev]
lto = "fat"

[profile.dev.package.esp-wifi]
opt-level = 3

[dependencies]
esp-hal = { version = "0.21.0" }
esp-backtrace = { version = "0.14.0", features = [
    "panic-handler",
    "println",
    "exception-handler",
] }
esp-println = { version = "0.12.0", features = ["log"] }
esp-hal-embassy = { version = "0.4.0", optional = true }

embassy-time = { version = "0.3.0", optional = true }
embassy-executor = { version = "=0.6.0", package = "embassy-executor", features = [
    "nightly",
    "integrated-timers",
], optional = true }
embassy-net = { version = "0.4.0", features = [
    "tcp",
    "udp",
    "dhcpv4",
    "medium-ethernet",
], optional = true }


esp-wifi = { version = "0.10.1", features = ["phy-enable-usb", "wifi-default"] }
smoltcp = { version = "0.11.0", default-features = false, features = [
    "proto-igmp",
    "proto-ipv4",
    "socket-tcp",
    "socket-icmp",
    "socket-udp",
    "medium-ethernet",
    "proto-dhcpv4",
    "socket-raw",
    "socket-dhcpv4",
] }
log = "0.4.16"
embedded-io = "0.6.1"
embedded-io-async = { version = "0.6.0", optional = true }
heapless = "0.8.0"
critical-section = "1.0.1"
static_cell = { version = "2.1", features = ["nightly"] }

esp-mbedtls = { path = "./esp-mbedtls" }

edge-http = { version = "0.3.0", optional = true }
edge-nal = { version = "0.3.0", optional = true }
edge-nal-embassy = { version = "0.3.0", optional = true }
cfg-if = "1.0.0"
esp-alloc = "0.5.0"

[[example]]
name = "crypto_self_test"
required-features = ["esp-wifi/sys-logs"]

[[example]]
name = "async_client"
required-features = ["async"]

[[example]]
name = "async_client_mTLS"
required-features = ["async"]

[[example]]
name = "async_server"
required-features = ["async"]

[[example]]
name = "async_server_mTLS"
required-features = ["async"]

[[example]]
name = "edge_server"
required-features = ["async", "edge-server"]

[features]
esp32 = [
    "esp-hal/esp32",
    "esp-hal-embassy?/esp32",
    "esp-backtrace/esp32",
    "esp-println/esp32",
    "esp-wifi/esp32",
    "esp-mbedtls/esp32",
]
esp32c3 = [
    "esp-hal/esp32c3",
    "esp-hal-embassy?/esp32c3",
    "esp-backtrace/esp32c3",
    "esp-println/esp32c3",
    "esp-wifi/esp32c3",
    "esp-mbedtls/esp32c3",
]
esp32s2 = [
    "esp-hal/esp32s2",
    "esp-hal-embassy?/esp32s2",
    "esp-backtrace/esp32s2",
    "esp-println/esp32s2",
    "esp-wifi/esp32s2",
    "esp-mbedtls/esp32s2",
]
esp32s3 = [
    "esp-hal/esp32s3",
    "esp-hal-embassy?/esp32s3",
    "esp-backtrace/esp32s3",
    "esp-println/esp32s3",
    "esp-wifi/esp32s3",
    "esp-mbedtls/esp32s3",
]
async = [
    "esp-wifi/async",
    "esp-wifi/embassy-net",
    "embassy-executor",
    "embassy-net",
    "embassy-time",
    "dep:embedded-io-async",
    "esp-mbedtls/async",
    "esp-hal-embassy",
]

# Helper feature to enable all dependencies required for edge-net
edge-server = [
    "edge-nal",
    "edge-nal-embassy",
    "edge-http",
    "esp-mbedtls/edge-nal",
]

# Patch until new release
[patch.crates-io]
edge-http = { git = "https://github.com/ivmarkov/edge-net" }
edge-nal = { git = "https://github.com/ivmarkov/edge-net" }
edge-nal-embassy = { git = "https://github.com/ivmarkov/edge-net" }

# Patch before 0.6.0 got yanked
embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "886580179ff250e15b0fad6448e8ebed6cdabf2b" }
embassy-time-driver = { git = "https://github.com/embassy-rs/embassy", rev = "886580179ff250e15b0fad6448e8ebed6cdabf2b" }
embassy-time-queue-driver = { git = "https://github.com/embassy-rs/embassy", rev = "886580179ff250e15b0fad6448e8ebed6cdabf2b" }