[package]
name = "examples"
version = "0.1.0"
authors = ["bjoernQ <bjoern.quentin@mobile-j.de>"]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.75"

[profile.release]
debug = true
lto = false

[profile.release.package.esp-wifi]
opt-level = 3

[profile.dev]
lto = false

[profile.dev.package.esp-wifi]
opt-level = 3

[dependencies]
esp-hal = { version = "0.20.1" }
esp-backtrace = { version = "0.14.0", features = [
    "panic-handler",
    "println",
    "exception-handler",
] }
esp-println = { version = "0.11.0", features = ["log"] }
esp-hal-embassy = { version = "0.3.0", optional = true }

embassy-time = { version = "0.3.0", optional = true }
embassy-executor = { version = "0.6.0", package = "embassy-executor", features = [
    "nightly",
    "integrated-timers",
], optional = true }
embassy-net = { version = "0.4.0", features = [
    "tcp",
    "udp",
    "dhcpv4",
    "medium-ethernet",
], optional = true }


esp-wifi = { version = "0.8.0", features = [
    "phy-enable-usb",
    "embedded-svc",
    "wifi-default",
] }
smoltcp = { version = "0.11.0", default-features = false, features = [
    "proto-igmp",
    "proto-ipv4",
    "socket-tcp",
    "socket-icmp",
    "socket-udp",
    "medium-ethernet",
    "proto-dhcpv4",
    "socket-raw",
    "socket-dhcpv4",
] }
log = "0.4.16"
embedded-io = "0.6.1"
embedded-io-async = { version = "0.6.0", optional = true }
heapless = "0.8.0"
critical-section = "1.0.1"
static_cell = { version = "2.1", features = ["nightly"] }

esp-mbedtls = { path = "./esp-mbedtls" }

edge-http = { package = "edge-http", git = "https://github.com/ivmarkov/edge-net/", optional = true }
edge-nal-embassy = { package = "edge-nal-embassy", git = "https://github.com/ivmarkov/edge-net/", optional = true }
cfg-if = "1.0.0"

[[example]]
name = "crypto_self_test"
required-features = ["esp-wifi/wifi-logs"]

[[example]]
name = "async_client"
required-features = ["async"]

[[example]]
name = "async_client_mTLS"
required-features = ["async"]

[[example]]
name = "async_server"
required-features = ["async"]

[[example]]
name = "async_server_mTLS"
required-features = ["async"]

[[example]]
name = "edge_server"
required-features = ["async", "esp-hal-embassy", "edge-nal-embassy", "edge-http", "esp-mbedtls/edge-nal"]

[features]
esp32 = [
    "esp-hal/esp32",
    "esp-backtrace/esp32",
    "esp-println/esp32",
    "esp-wifi/esp32",
    "esp-mbedtls/esp32",
]
esp32c3 = [
    "esp-hal/esp32c3",
    "esp-backtrace/esp32c3",
    "esp-println/esp32c3",
    "esp-wifi/esp32c3",
    "esp-mbedtls/esp32c3",
]
esp32s2 = [
    "esp-hal/esp32s2",
    "esp-backtrace/esp32s2",
    "esp-println/esp32s2",
    "esp-wifi/esp32s2",
    "esp-mbedtls/esp32s2",
]
esp32s3 = [
    "esp-hal/esp32s3",
    "esp-backtrace/esp32s3",
    "esp-println/esp32s3",
    "esp-wifi/esp32s3",
    "esp-mbedtls/esp32s3",
]
async = [
    "esp-wifi/async",
    "esp-wifi/embassy-net",
    "embassy-executor",
    "embassy-net",
    "embassy-time",
    "dep:embedded-io-async",
    "esp-mbedtls/async",
    "esp-hal/async",
]
