[package]
name = "esp-mbedtls-sys"
version = "0.1.0"
edition = "2021"

[build-dependencies]
anyhow = "1.0.68"

[dependencies]

[features]
default = []

# ESP-baremetal: Exactly *one* chip MUST be selected via its feature:
esp32 = []
esp32c3 = []
esp32s2 = []
esp32s3 = []

[target.'cfg(target_os = "espidf")'.dependencies]
esp-idf-sys = { version = "0.35", default-features = false }
