[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --baud 921600"

rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Trom_functions.x",
]

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor --baud 921600"

rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-Trom_functions.x",

  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

[target.xtensa-esp32s2-none-elf]
runner = "espflash flash --monitor --baud 921600"

rustflags = [
    #"-C", "linker=rust-lld",    
    "-C", "link-arg=-Tlinkall.x",
    "-C", "link-arg=-Trom_functions.x",
]

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --baud 921600"

rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Trom_functions.x",
]

[unstable]
build-std = ["core"]

[alias]
xtask = "run --manifest-path ./xtask/Cargo.toml --"


# Alias' for quickly building for different chips or running examples
# By default we enable
#   - `default` HAL features to set up basic chip specific settings
esp32 =   "run --features   esp32 --target xtensa-esp32-none-elf        --features esp-hal/default"
esp32s2 = "run --features esp32s2 --target xtensa-esp32s2-none-elf      --features esp-hal/default"
esp32s3 = "run --features esp32s3 --target xtensa-esp32s3-none-elf      --features esp-hal/default"
esp32c3 = "run --features esp32c3 --target riscv32imc-unknown-none-elf  --features esp-hal/default"

besp32 =   "build --features   esp32 --target xtensa-esp32-none-elf        --features esp-hal/default"
besp32s2 = "build --features esp32s2 --target xtensa-esp32s2-none-elf      --features esp-hal/default"
besp32s3 = "build --features esp32s3 --target xtensa-esp32s3-none-elf      --features esp-hal/default"
besp32c3 = "build --features esp32c3 --target riscv32imc-unknown-none-elf  --features esp-hal/default"
