[package]
name = "esp-mbedtls"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-mbedtls-sys = { path = "../esp-mbedtls-sys" }
log = "0.4.17"
embedded-io = { version = "0.6.1" }
embedded-io-async = { version = "0.6.0", optional = true }
esp32-hal = { version = "0.16.0", optional = true }
esp32c3-hal = { version = "0.13.0", optional = true }
esp32s2-hal = { version = "0.13.0", optional = true }
esp32s3-hal = { version = "0.13.0", optional = true }

[features]
async = ["dep:embedded-io-async"]
esp32 = ["esp32-hal", "esp-mbedtls-sys/esp32"]
esp32c3 = ["esp32c3-hal", "esp-mbedtls-sys/esp32c3"]
esp32s2 = ["esp32s2-hal", "esp-mbedtls-sys/esp32s2"]
esp32s3 = ["esp32s3-hal", "esp-mbedtls-sys/esp32s3"]
