[package]
name = "esp-mbedtls"
version = "0.1.0"
edition = "2021"
rust-version = "1.74"

[lib]
harness = false

[dependencies]
esp-mbedtls-sys = { path = "../esp-mbedtls-sys" }
log = "0.4.17"
embedded-io = { version = "0.6.1" }
embedded-io-async = { version = "0.6.0", optional = true }
esp-hal = { version = "0.21.0", optional = true }
cfg-if = "1.0.0"
edge-nal = { version = "0.3.0", optional = true }
critical-section = "1.1.3"
crypto-bigint = { version = "0.5.3", optional = true, default-features = false, features = ["extra-sizes"] }

[features]
default = ["edge-nal"]
async = ["dep:embedded-io-async"]
esp32 = ["esp-hal/esp32", "esp-mbedtls-sys/esp32", "crypto-bigint"]
esp32c3 = ["esp-hal/esp32c3", "esp-mbedtls-sys/esp32c3", "crypto-bigint"]
esp32s2 = ["esp-hal/esp32s2", "esp-mbedtls-sys/esp32s2", "crypto-bigint"]
esp32s3 = ["esp-hal/esp32s3", "esp-mbedtls-sys/esp32s3", "crypto-bigint"]

# Implement the traits defined in the latest HEAD of `edge-nal`
edge-nal = ["dep:edge-nal", "async"]
