[package]
name = "esp-mbedtls"
version = "0.1.0"
edition = "2021"
rust-version = "1.74"

[dependencies]
esp-mbedtls-sys = { path = "../esp-mbedtls-sys" }
log = "0.4.17"
embedded-io = { version = "0.6.1" }
embedded-io-async = { version = "0.6.0", optional = true }
crypto-bigint = { version = "0.5.3", default-features = false, features = ["extra-sizes"] }
esp-hal = { version = "0.21.0" }
cfg-if = "1.0.0"
edge-nal = { version = "0.3.0", optional = true }
edge-nal-embassy = { version = "0.3.0", optional = true }
embassy-net = { version = "0.4", features = [ "tcp", "medium-ethernet"], optional = true }

[features]
async = ["dep:embedded-io-async"]
esp32 = ["esp-hal/esp32", "esp-mbedtls-sys/esp32"]
esp32c3 = ["esp-hal/esp32c3", "esp-mbedtls-sys/esp32c3"]
esp32s2 = ["esp-hal/esp32s2", "esp-mbedtls-sys/esp32s2"]
esp32s3 = ["esp-hal/esp32s3", "esp-mbedtls-sys/esp32s3"]

# Implement the traits defined in the latest HEAD of `edge-nal`
edge-nal = ["dep:edge-nal", "dep:edge-nal-embassy", "dep:embassy-net"]
